// <auto-generated />
using System;
using BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp.Data.Migrations
{
    [DbContext(typeof(BudgetContext))]
    partial class BudgetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.4.21253.1");

            modelBuilder.Entity("BlazorApp.Data.Models.Budget", b =>
                {
                    b.Property<int>("YearMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("YearMonth");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("BlazorApp.Data.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BudgetYearMonth")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetYearMonth");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("BlazorApp.Data.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BudgetYearMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetYearMonth");

                    b.ToTable("Income");
                });

            modelBuilder.Entity("BlazorApp.Data.Models.Expense", b =>
                {
                    b.HasOne("BlazorApp.Data.Models.Budget", null)
                        .WithMany("Expenses")
                        .HasForeignKey("BudgetYearMonth");
                });

            modelBuilder.Entity("BlazorApp.Data.Models.Income", b =>
                {
                    b.HasOne("BlazorApp.Data.Models.Budget", null)
                        .WithMany("Incomes")
                        .HasForeignKey("BudgetYearMonth");
                });

            modelBuilder.Entity("BlazorApp.Data.Models.Budget", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
